name: voila
channels:
  - conda-forge
dependencies:
  - ipyvolume
  - bqplot
  - scipy
  - ipympl
  - xleaflet=0.11.1
  - xeus-cling=0.8.1
  - pip:
    - voila-vuetify
    - git://github.com/cailiang9/voila.git@patch-1
